export interface category {
    id: string,
    name: string
}

export const PodcastCategories : Array<category> = [
    { id: "01-00", name: "Arts" },
    { id: "01-01", name: "Arts > Design" },
    { id: "01-02", name: "Arts > Fashion & Beauty" },
    { id: "01-03", name: "Arts > Food" },
    { id: "01-04", name: "Arts > Books" },
    { id: "01-05", name: "Arts > Performing Arts" },
    { id: "01-06", name: "Arts > Visual Arts" },
    
    { id: "02-00", name: "Business" },
    { id: "02-02", name: "Business > Careers" },
    { id: "02-03", name: "Business > Investing" },
    { id: "02-04", name: "Business > Management" },
    { id: "02-06", name: "Business > Entrepreneurship" },
    { id: "02-07", name: "Business > Marketing" },
    { id: "02-08", name: "Business > Non-Profit" },

    { id: "03-00", name: "Comedy" },
    { id: "03-01", name: "Comedy > Comedy Interviews" },
    { id: "03-02", name: "Comedy > Improv" },
    { id: "03-03", name: "Comedy > Stand-Up" },

    { id: "04-00", name: "Education" },
    { id: "04-04", name: "Education > Language Learning" },
    { id: "04-05", name: "Education > Courses" },
    { id: "04-06", name: "Education > How To" },
    { id: "04-07", name: "Education > Self-Improvement" },

    { id: "20-00", name: "Fiction" },
    { id: "20-01", name: "Fiction > Comedy Fiction" },
    { id: "20-02", name: "Fiction > Drama" },
    { id: "20-03", name: "Fiction > Science Fiction" },

    { id: "06-00", name: "Government"},

    { id: "30-00", name: "History" },

    { id: "07-00", name: "Health & Fitness" },
    { id: "07-01", name: "Health & Fitness > Alternative Health" },
    { id: "07-02", name: "Health & Fitness > Fitness" },
    { id: "07-04", name: "Health & Fitness > Sexuality" },
    { id: "07-05", name: "Health & Fitness > Medicine" },
    { id: "07-06", name: "Health & Fitness > Mental Health" },
    { id: "07-07", name: "Health & Fitness > Nutrition" },

    { id: "08-00", name: "Kids & Family" },
    { id: "08-01", name: "Kids & Family > Education for Kids" },
    { id: "08-02", name: "Kids & Family > Parenting" },
    { id: "08-03", name: "Kids & Family > Pets & Animals" },
    { id: "08-04", name: "Kids & Family > Stories for Kids" },

    { id: "40-00", name: "Leisure" },
    { id: "40-01", name: "Leisure > Animation & Manga" },
    { id: "40-02", name: "Leisure > Automotive" },
    { id: "40-03", name: "Leisure > Aviation" },
    { id: "40-04", name: "Leisure > Crafts" },
    { id: "40-05", name: "Leisure > Games" },
    { id: "40-06", name: "Leisure > Hobbies" },
    { id: "40-07", name: "Leisure > Home & Garden" },
    { id: "40-08", name: "Leisure > Video Games" },

    { id: "09-00", name: "Music" },
    { id: "09-01", name: "Music > Music Commentary" },
    { id: "09-02", name: "Music > Music History" },
    { id: "09-03", name: "Music > Music Interviews" },

    { id: "10-00", name: "News" },
    { id: "10-01", name: "News > Business News" },
    { id: "10-02", name: "News > Daily News" },
    { id: "10-03", name: "News > Entertainment News" },
    { id: "10-04", name: "News > News Commentary" },
    { id: "10-05", name: "News > Politics" },
    { id: "10-06", name: "News > Sports News" },
    { id: "10-07", name: "News > Tech News" },

    { id: "11-00", name: "Religion & Spirituality" },
    { id: "11-01", name: "Religion & Spirituality > Buddhism" },
    { id: "11-02", name: "Religion & Spirituality > Christianity" },
    { id: "11-03", name: "Religion & Spirituality > Hinduism" },
    { id: "11-04", name: "Religion & Spirituality > Islam" },
    { id: "11-05", name: "Religion & Spirituality > Judaism" },
    { id: "11-06", name: "Religion & Spirituality > Religion" },
    { id: "11-07", name: "Religion & Spirituality > Spirituality" },

    { id: "12-00", name: "Science" },
    { id: "12-01", name: "Science > Medicine" },
    { id: "12-02", name: "Science > Natural Sciences" },
    { id: "12-03", name: "Science > Social Sciences" },
    { id: "12-04", name: "Science > Astronomy" },
    { id: "12-05", name: "Science > Chemistry" },
    { id: "12-06", name: "Science > Earth Sciences" },
    { id: "12-07", name: "Science > Life Sciences" },
    { id: "12-08", name: "Science > Mathematics" },
    { id: "12-09", name: "Science > Nature" },
    { id: "12-10", name: "Science > Physics" },

    { id: "13-00", name: "Society & Culture" },
    { id: "13-02", name: "Society & Culture > Personal Journals" },
    { id: "13-03", name: "Society & Culture > Philosophy" },
    { id: "13-04", name: "Society & Culture > Places & Travel" },
    { id: "13-05", name: "Society & Culture > Relationships" },
    { id: "13-06", name: "Society & Culture > Documentary" },

    { id: "14-00", name: "Sports" },
    { id: "14-05", name: "Sports > Baseball" },
    { id: "14-06", name: "Sports > Basketball" },
    { id: "14-07", name: "Sports > Cricket" },
    { id: "14-08", name: "Sports > Fantasy Sports" },
    { id: "14-09", name: "Sports > Football" },
    { id: "14-10", name: "Sports > Golf" },
    { id: "14-11", name: "Sports > Hockey" },
    { id: "14-12", name: "Sports > Rugby" },
    { id: "14-13", name: "Sports > Running" },
    { id: "14-14", name: "Sports > Soccer" },
    { id: "14-15", name: "Sports > Swimming" },
    { id: "14-16", name: "Sports > Tennis" },
    { id: "14-17", name: "Sports > Volleyball" },
    { id: "14-18", name: "Sports > Wilderness" },
    { id: "14-19", name: "Sports > Wrestling" },

    { id: "15-00", name: "Technology" },

    { id: "50-00", name: "True Crime" },

    { id: "16-00", name: "TV & Film" },
    { id: "16-01", name: "TV & Film > After Shows" },
    { id: "16-02", name: "TV & Film > Film History" },
    { id: "16-03", name: "TV & Film > Film Interviews" },
    { id: "16-04", name: "TV & Film > Film Reviews" },
    { id: "16-05", name: "TV & Film > TV Reviews" }
]