version: "0.5"

processes:
  server:
   command: mix run --no-halt
   working_dir: server
   environment:
    - "PORT=9000"
    - "MIX_ENV=prod"
   ready_log_line: "Running PublisherWeb.Endpoint with Bandit"
   availability:
    restart: "always"
