name: 'Cache'
runs:
  using: "composite"
  steps:
    - name: Cache Client
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        path: ./client/node_modules
    - name: Cache Server
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        path: ./client/node_modules
    - name: Install Devbox
      uses: jetpack-io/devbox-install-action@v0.8.0

