# Extend from the official Elixir image
FROM elixir:1.17.1

RUN mkdir /app

COPY server /app

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force && mix deps.get

EXPOSE 4000

CMD ["mix", "run", "--no-halt"]
