name: Production
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Remote
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: services.podlove.org
        username: root
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        script: |
          mkdir -p app
          cd app
          ( [ ! -d ".git" ] && git clone git@github.com:podlove/publisher-services.git . ) || true

    - name: Deploy to production environment
      uses: appleboy/ssh-action@v1.0.3
      env:
        SHA: ${{ github.sha }}
        VITE_BUILD: ${{ github.sha }}
        HONEYBADGER_API_KEY: ${{ secrets.HONEYBADGER_KEY }}
      with:
        host: services.podlove.org
        username: root
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        envs: SHA,VITE_BUILD
        script:  |
          cd app
          git fetch
          git reset --hard $SHA
          devbox install
          devbox services down
          devbox run bootstrap
          devbox run build
          devbox services up --background
