name: Unit Tests
on:
  pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-unit-tests
  cancel-in-progress: true

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/environment
      - name: Bootstrap Environment
        run: devbox run bootstrap

  build:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/environment
      - name: Build
        run: devbox run build

  test:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/environment
      - name: Test
        run: devbox run test
